version: "2"
plugins:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
checks:
  file-lines:
    config:
      threshold: 300
  method-lines:
    config:
      threshold: 30
  method-complexity:
    config:
      threshold: 7
  similar-code:
    enabled: false
  identical-code:
    enabled: false
include_patterns:
  - '**.js'
